server:
  port: 9000
spring:
  application:
    name: cloud
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
